name: Unlock Prod Deploy

on:
  workflow_dispatch:
    inputs:
      product:
        description: 'The product name (as shown in your plan step)'
        required: true

jobs:
  release-lock:
    runs-on: ubuntu-latest
    steps:
      - name: 🔓 Release prod lock
        uses: softprops/turnstyle@v2
        with:
          lock: prod-deploy-${{ github.event.inputs.product }}
          run: unlock
